# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Article.destroy_all
Category.destroy_all

c1 = Category.create(title: "Mountain biking")
 
c2 = Category.create(title: "Hiking")

Article.create(title: 'Mountain biking the Thunderbird Gardens', summary: "Lots of trail, but most of it is more of a hassle to ride than a joy.", text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris euismod urna sit amet justo sodales maximus. Aliquam erat volutpat. Maecenas pretium mauris id nulla sollicitudin sagittis et eget elit. Nulla consectetur arcu vel faucibus pulvinar. Pellentesque tincidunt elementum lacus, et eleifend nibh consectetur quis. Donec eget libero a neque dignissim faucibus ut nec turpis. Nulla facilisi.</p>
	<p>Nam venenatis ex non sollicitudin eleifend. Cras in lacus placerat, faucibus nisl sed, suscipit ligula. Aenean fringilla quam non luctus mollis. Etiam rhoncus, massa ut fermentum dignissim, enim nibh ultricies felis, id feugiat sapien erat rhoncus sem. Cras eget ante ultricies, vehicula mauris quis, consectetur elit. Quisque condimentum, lectus vel imperdiet sagittis, urna lectus porta metus, vitae tempus elit lacus nec nisl. Nullam suscipit tellus a urna finibus posuere. Ut ex ligula, porttitor eget tellus quis, venenatis sagittis nunc. Aenean ut dolor at magna malesuada pellentesque. Pellentesque scelerisque, ligula aliquam feugiat fringilla, ligula libero suscipit tortor, id euismod velit urna non lectus. Phasellus venenatis est sit amet tempus porttitor.</p>
	<p>Nullam viverra ornare erat, quis gravida lacus consectetur sit amet. Maecenas semper tristique diam non sollicitudin. In maximus hendrerit vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent porta eros nisi, vel congue arcu laoreet sit amet. Vestibulum convallis, enim nec tempus dignissim, mauris dolor lobortis sem, eleifend aliquet lacus arcu id sem. Aenean fringilla tortor nec lorem varius placerat eget nec ipsum. Quisque malesuada non leo eu bibendum. Sed fringilla a purus vitae consectetur. Praesent fringilla quam eu ante tristique, at feugiat nunc ultricies. Mauris maximus, augue vel varius finibus, lacus massa hendrerit risus, nec vestibulum erat nunc non tellus. Aenean erat tortor, feugiat et elit a, posuere viverra nibh. Aliquam ullamcorper est eget nibh rutrum, nec laoreet ex porttitor.</p>', author: 'Payton', visible: true, category_id: c1.id)

Article.create(title: 'When Lake Powell Freezes Over', summary: "Visiting Lake Powell in the winter is a great way to escape the crowd and enjoy some hiking.", text: '<p>Quisque nec nulla quis odio sodales maximus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur velit ipsum, maximus a blandit at, placerat eget lorem. Donec sagittis hendrerit justo, id aliquet eros sollicitudin non. Nullam scelerisque vitae arcu ut interdum. Aliquam erat volutpat. Nam aliquet, eros eu porta iaculis, sapien ligula gravida mi, at lacinia velit turpis vel tellus.</p>
	<p>Morbi suscipit lorem eget molestie consequat. Maecenas eu nisi quis magna tincidunt gravida sed vitae risus. Etiam tristique molestie neque ut fringilla. Praesent ullamcorper ut mauris non commodo. Aliquam tristique orci a eros aliquam, sit amet iaculis sem rutrum. Etiam pharetra, nunc et convallis imperdiet, felis odio pharetra nunc, id consectetur nunc urna porttitor sapien. Nunc malesuada metus nec risus tempor feugiat. Aenean consequat, est ut dignissim ornare, lorem odio eleifend lectus, nec consequat est metus sit amet eros. Nunc aliquet dui velit, at mollis mi suscipit id. Aliquam vestibulum velit velit. Sed efficitur nulla lacus, ut eleifend est pretium ac. Praesent condimentum pharetra risus, sed vestibulum justo auctor at. Etiam dignissim lacinia ligula vel tincidunt. Curabitur rhoncus vel ex et laoreet.</p>', author: 'Payton', visible: true, category_id: c2.id)

Article.create(title: 'How to Not Hike a Slot Canyon', summary: "Winter slot canyon adventures are a lot more fun when you're not wearing shorts and running shoes.", text: '<p>Duis pharetra sapien vel volutpat ullamcorper. Praesent ornare, risus in finibus euismod, eros diam ullamcorper tortor, nec interdum felis enim luctus libero. In vitae odio luctus urna condimentum congue. Pellentesque eu sollicitudin dui, et condimentum lectus. Integer facilisis tortor eu semper faucibus. Donec et erat hendrerit, cursus ante sit amet, sodales risus. Fusce eu sapien sit amet nisl ornare vehicula. Suspendisse pellentesque nisl arcu, id volutpat dolor lacinia eget. Quisque vehicula enim eget aliquam volutpat. Phasellus dictum nulla quis rhoncus varius. Curabitur posuere quam quis scelerisque ultricies.</p>
	<p>Integer nisi lorem, vulputate quis dignissim ac, fermentum quis augue. Sed pretium enim at tincidunt tristique. In cursus urna risus, nec lobortis lacus rutrum lacinia. Maecenas tincidunt turpis sem, eget rutrum eros egestas ut. Cras scelerisque porta fringilla. Aenean tellus tellus, congue nec posuere sed, tristique vel turpis. Integer quis purus risus. Nam lobortis massa ut nunc hendrerit, sagittis suscipit sem efficitur. Sed fermentum nisi fringilla euismod sodales. Aenean condimentum fringilla dapibus. Donec fermentum tellus arcu, in varius purus commodo sit amet. Integer efficitur mi vitae nunc sagittis, nec sollicitudin quam mattis. Praesent at tempor nisl, non molestie nunc. Fusce velit metus, convallis vel sem id, lobortis pellentesque diam. Vestibulum id eleifend nulla. Aenean molestie tristique tellus, non maximus est posuere sit amet.</p>', author: 'Ryan', visible: true, category_id: c2.id)